spring: 
  session:
    timeout: 604800000
    #   3600 * 1000 * 24 * 7
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /book/
      suffix: .jsp
    
renren:
  cluster: true  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  globalSessionTimeout: 3600   #单机环境，session过期时间为60分钟
  redis:
    open: true  #是否开启redis缓存  true开启   false关闭
  
mybatis-plus: 
  mapper-locations: classpath:mappers/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.Yang.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
  

###全局接收预警邮箱
warning: 
   mail: 
      address: 724555508@qq.com
      
###雪扬科技（手机尾号:7668）
aliyun: 
  sms: 
    accessKeyID: LTAIrp1AoFqosKaU
    accessKeySecret:  qwjqIAafq5QO1c3iMDJwRWKAz5cC31
    messageType: SmsReport
##阿里云短信回执队列
    queueName: Alicom-Queue-1207243149952449-SmsReport
##设置超时时间-可自行调整（默认  10000）
    clientConnectTime: 10000
    clientReadTime: 10000